TOMCAT_HOME=/opt/tomcat7
JAVA_HOME=/opt/java/jdk16
CATALINA_OPTS="-Xmx1024m 
-Dorg.apache.el.parser.SKIP_IDENTIFIER_CHECK=true
-Dcom.sun.management.jmxremote
-Dcom.sun.management.jmxremote.port=1011
-Dcom.sun.management.jmxremote.ssl=false
-Dcom.sun.management.jmxremote.authenticate=false
-Duser.timezone=America/Sao_Paulo
-Dfile.encoding=ISO-8859-1 
-Duser.country=BR 
-Duser.language=pt
-Djava.awt.headless=true
-server
-XX:+UseConcMarkSweepGC
-XX:+UseParNewGC
-XX:+UseCMSInitiatingOccupancyOnly
-XX:CMSInitiatingOccupancyFraction=40
-XX:+CMSPermGenSweepingEnabled
-XX:+CMSClassUnloadingEnabled
-XX:MaxPermSize=256M
-XX:ReservedCodeCacheSize=256M
-XX:HeapDumpPath=/opt/tomcat7/HeapDump"
