version: '3.9'
services:
  metabase:
    image: metabase/metabase:v0.44.3
    container_name: metabase
    hostname: metabase
    volumes:
    - /dev/urandom:/dev/random:ro
    - ./metabase_data:/metabase-data
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase_prd
      MB_DB_PORT: 5432
      MB_DB_USER_FILE: /run/secrets/db_user
      MB_DB_PASS_FILE: /run/secrets/db_password
      MB_DB_HOST: postgres
      JAVA_TIMEZONE: America/Sao_Paulo
    networks:
      - metabase-net
    depends_on:
      - postgres
    secrets:
      - db_password
      - db_user
    labels:
      ambiente-qas: "false"        
  postgres:
    image: postgres:12.12-bullseye
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_DB: metabase_prd
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    networks:
      - metabase-net
    secrets:
      - db_password
      - db_user
    volumes:
      - ./pg_data:/var/lib/postgresql/data  
networks:
  metabase-net:
    driver: bridge
secrets:
   db_password:
     file: db_password
   db_user:
     file: db_user
